spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: hbcustomer
    url: jdbc:mysql://localhost:3306/customerdb
    password: hbcustomer_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
